version: '2'

services:
  opensirenedb:
    build:
      dockerfile: db.Dockerfile
      context: .
    hostname: 127.0.0.1
    ports:
      - 5432:5432
    network_mode: "host"

  metabase:
    image: metabase/metabase
    hostname: 127.0.0.1
    network_mode: "host"